'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.269
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VelerSoftware.SZVB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Abandonner.
        '''</summary>
        Friend ReadOnly Property AbortText() As String
            Get
                Return ResourceManager.GetString("AbortText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Abandon.
        '''</summary>
        Friend ReadOnly Property AbortText_EN() As String
            Get
                Return ResourceManager.GetString("AbortText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowHovered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowHovered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend ReadOnly Property CancelText() As String
            Get
                Return ResourceManager.GetString("CancelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend ReadOnly Property CancelText_EN() As String
            Get
                Return ResourceManager.GetString("CancelText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ChevronLess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevronLess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChevronLessHovered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevronLessHovered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChevronLessPressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevronLessPressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChevronMore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevronMore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChevronMoreHovered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevronMoreHovered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChevronMorePressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevronMorePressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Fermer.
        '''</summary>
        Friend ReadOnly Property CloseText() As String
            Get
                Return ResourceManager.GetString("CloseText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Close.
        '''</summary>
        Friend ReadOnly Property CloseText_EN() As String
            Get
                Return ResourceManager.GetString("CloseText_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Plus de détails.
        '''</summary>
        Friend ReadOnly Property CollapsedText() As String
            Get
                Return ResourceManager.GetString("CollapsedText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à More details.
        '''</summary>
        Friend ReadOnly Property CollapsedText_EN() As String
            Get
                Return ResourceManager.GetString("CollapsedText_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Continuer.
        '''</summary>
        Friend ReadOnly Property ContinueText() As String
            Get
                Return ResourceManager.GetString("ContinueText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Continue.
        '''</summary>
        Friend ReadOnly Property ContinueText_EN() As String
            Get
                Return ResourceManager.GetString("ContinueText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Error_VistaDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_VistaDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moins de détails.
        '''</summary>
        Friend ReadOnly Property ExpandedText() As String
            Get
                Return ResourceManager.GetString("ExpandedText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Less details.
        '''</summary>
        Friend ReadOnly Property ExpandedText_EN() As String
            Get
                Return ResourceManager.GetString("ExpandedText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Ignorer.
        '''</summary>
        Friend ReadOnly Property IgnoreText() As String
            Get
                Return ResourceManager.GetString("IgnoreText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Ignore.
        '''</summary>
        Friend ReadOnly Property IgnoreText_EN() As String
            Get
                Return ResourceManager.GetString("IgnoreText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info_bar_close_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_bar_close_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info_bar_close_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_bar_close_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info_bar_close_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_bar_close_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rien.
        '''</summary>
        Friend ReadOnly Property NoneText() As String
            Get
                Return ResourceManager.GetString("NoneText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à None.
        '''</summary>
        Friend ReadOnly Property NoneText_EN() As String
            Get
                Return ResourceManager.GetString("NoneText_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Non.
        '''</summary>
        Friend ReadOnly Property NoText() As String
            Get
                Return ResourceManager.GetString("NoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;No.
        '''</summary>
        Friend ReadOnly Property NoText_EN() As String
            Get
                Return ResourceManager.GetString("NoText_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Non pour tous.
        '''</summary>
        Friend ReadOnly Property NoToAllText() As String
            Get
                Return ResourceManager.GetString("NoToAllText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No to all.
        '''</summary>
        Friend ReadOnly Property NoToAllText_EN() As String
            Get
                Return ResourceManager.GetString("NoToAllText_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Friend ReadOnly Property OKText() As String
            Get
                Return ResourceManager.GetString("OKText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Friend ReadOnly Property OKText_EN() As String
            Get
                Return ResourceManager.GetString("OKText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Réessayer.
        '''</summary>
        Friend ReadOnly Property RetryText() As String
            Get
                Return ResourceManager.GetString("RetryText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Retry.
        '''</summary>
        Friend ReadOnly Property RetryText_EN() As String
            Get
                Return ResourceManager.GetString("RetryText_EN", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecurityError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecurityError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecurityQuestion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecurityQuestion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecuritySuccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecuritySuccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecurityWarning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecurityWarning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallInformation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallInformation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallQuestion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallQuestion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallSecurity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallSecurity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallSecurityError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallSecurityError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallSecurityQuestion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallSecurityQuestion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallSecuritySucess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallSecuritySucess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallSecurityWarning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallSecurityWarning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallWarning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallWarning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning_VistaDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_VistaDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Win8_WizardButton_disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_WizardButton_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Win8_WizardButton_hot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_WizardButton_hot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Win8_WizardButton_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_WizardButton_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Win8_WizardButton_pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_WizardButton_pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WizardButton_disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardButton_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WizardButton_hot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardButton_hot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WizardButton_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardButton_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WizardButton_pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WizardButton_pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Oui.
        '''</summary>
        Friend ReadOnly Property YesText() As String
            Get
                Return ResourceManager.GetString("YesText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Yes.
        '''</summary>
        Friend ReadOnly Property YesText_EN() As String
            Get
                Return ResourceManager.GetString("YesText_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Oui pour tous.
        '''</summary>
        Friend ReadOnly Property YesToAllText() As String
            Get
                Return ResourceManager.GetString("YesToAllText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Yes to all.
        '''</summary>
        Friend ReadOnly Property YesToAllText_EN() As String
            Get
                Return ResourceManager.GetString("YesToAllText_EN", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
