'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.269
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SoftwareZator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _305_Close_16x16_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_305_Close_16x16_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _305_Close_32x32_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_305_Close_32x32_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property About_Box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About_Box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property About_Box_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About_Box_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Activer_SZ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Activer_SZ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Activer_Sz_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Activer_Sz_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property actualiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actualiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_ctrl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_ctrl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AdvancedInstaller_en() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedInstaller_en", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AdvancedInstaller_fr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedInstaller_fr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AjustHeight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjustHeight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AjustHeightAndWeight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjustHeightAndWeight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AjustToGrid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjustToGrid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AjustWeight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjustWeight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignObjectsBottomHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignObjectsBottomHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignObjectsCenteredHorizontalHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignObjectsCenteredHorizontalHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignObjectsCenteredVerticalHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignObjectsCenteredVerticalHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignObjectsLeftHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignObjectsLeftHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignObjectsRightHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignObjectsRightHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignObjectsTopHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignObjectsTopHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignToGridHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignToGridHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlignToGridHS_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignToGridHS_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bases_de_donnees() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bases_de_donnees", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Boite_a_outils() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boite_a_outils", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakpoint_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakpoint_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakpoint_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakpoint_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakpoint_delete_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakpoint_delete_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakpoint_delete_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakpoint_delete_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakpoint_disabled_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakpoint_disabled_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakpoint_disabled_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakpoint_disabled_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BringToFrontHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BringToFrontHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C_File_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_File_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C_File_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_File_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CenterHorizontal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CenterHorizontal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CenterVertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CenterVertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chart_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChuckNorris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChuckNorris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property correction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_mysql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_mysql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_oracle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_oracle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_sql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_sql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_MoveNextHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Debogguer_Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debogguer_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Debugger_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debugger_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Debugger_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debugger_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Debugger_Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debugger_Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Debugger_Restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debugger_Restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_en_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_en_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Didac_fr_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Didac_fr_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property effacer_tout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("effacer_tout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EtienneBaudoux() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EtienneBaudoux", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Executer_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Executer_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Executer_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Executer_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explorateur_de_solutions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explorateur_de_solutions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exporter_VS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exporter_VS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exporter_VS_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exporter_VS_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property facebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property feedback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feedback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Feedback_Bad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Feedback_Bad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property feedback_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feedback_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Feedback_Good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Feedback_Good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Feedback_Ideas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Feedback_Ideas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fichier_BMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fichier_BMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fichier_Code() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fichier_Code", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fichier_Fenetre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fichier_Fenetre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fichier_Inconnu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fichier_Inconnu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fichier_Statistiques() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fichier_Statistiques", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fichier_Texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fichier_Texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fonction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fonction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fonction_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fonction_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Generer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Generer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Generer_Obfuscation_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Generer_Obfuscation_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Generer_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Generer_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gest_var() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gest_var", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gestionnaire_plugins_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gestionnaire_plugins_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gestionnaire_plugins_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gestionnaire_plugins_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconContainer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconContainer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property modifier_action() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_action", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property modifier_action_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_action_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property modifyvarBIG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifyvarBIG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nouveau_dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nouveau_dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nouveau_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nouveau_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nouveau_Fichier_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nouveau_Fichier_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nouveau_Projet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nouveau_Projet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nouveau_Projet_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nouveau_Projet_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nouvelle_bases_de_donnees() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nouvelle_bases_de_donnees", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nouvelle_bases_de_donnees_existante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nouvelle_bases_de_donnees_existante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nouvelle_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nouvelle_table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ordre_Generation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ordre_Generation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ordre_tabulation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordre_tabulation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ouvrir_Projet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ouvrir_Projet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ouvrir_Projet_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ouvrir_Projet_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_de_demarrage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_de_demarrage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_de_demarrage_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_de_demarrage_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PageLayoutLarge_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PageLayoutLarge_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PageLayoutLarge_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PageLayoutLarge_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property parametre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("parametre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Partner_Component_Factory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Partner_Component_Factory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Partner_Microsoft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Partner_Microsoft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Partner_MySql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Partner_MySql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Partner_Sql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Partner_Sql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste_sma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_sma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property presse_papiers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("presse_papiers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_before() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_before", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_before_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_before_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_fast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_fast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_fast_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_fast_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Project_Application_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Project_Application_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Project_DLL_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Project_DLL_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Project_Icon_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Project_Icon_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Propriété() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Propriété", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ProtectFormHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProtectFormHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reduire_Projet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reduire_Projet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_all_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_all_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_as() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_as", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_as_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_as_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_project() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_project", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SendToBackHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendToBackHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sortie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpaceDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpaceDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpaceDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpaceDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpaceEqual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpaceEqual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpaceUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpaceUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SplashScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Style_XP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Style_XP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SZ_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SZ_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SZ_Icon_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SZ_Icon_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property twitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property var_ajouter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("var_ajouter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property var_modifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("var_modifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property var_supprimer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("var_supprimer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VB_File() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VB_File", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VB_File_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VB_File_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Visual_Studio_2010_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Visual_Studio_2010_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Didac_en_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Didac_en_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Didac_en_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Didac_en_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Didac_en_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Didac_en_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Didac_fr_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Didac_fr_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Didac_fr_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Didac_fr_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vocale_Didac_fr_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vocale_Didac_fr_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Voice_Progress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voice_Progress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomIn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomIn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomIn_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomIn_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomOut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomOut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomOut_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomOut_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomReset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomReset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomReset_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomReset_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
