'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.269
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        '''<summary>
        '''Langue du logiciel
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Langue du logiciel"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Langue() As String
            Get
                Return CType(Me("Langue"),String)
            End Get
            Set
                Me("Langue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Nom_Utilisateur() As String
            Get
                Return CType(Me("Nom_Utilisateur"),String)
            End Get
            Set
                Me("Nom_Utilisateur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Société() As String
            Get
                Return CType(Me("Société"),String)
            End Get
            Set
                Me("Société") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Emplacement_Project_Par_Defaut() As String
            Get
                Return CType(Me("Emplacement_Project_Par_Defaut"),String)
            End Get
            Set
                Me("Emplacement_Project_Par_Defaut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Ouvrir_Page_De_Démarrage() As Boolean
            Get
                Return CType(Me("Ouvrir_Page_De_Démarrage"),Boolean)
            End Get
            Set
                Me("Ouvrir_Page_De_Démarrage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Verifier_Mise_A_Jours() As Boolean
            Get
                Return CType(Me("Verifier_Mise_A_Jours"),Boolean)
            End Get
            Set
                Me("Verifier_Mise_A_Jours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Afficher_La_Griller() As Boolean
            Get
                Return CType(Me("Afficher_La_Griller"),Boolean)
            End Get
            Set
                Me("Afficher_La_Griller") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Aimentation_Intelligente() As Boolean
            Get
                Return CType(Me("Aimentation_Intelligente"),Boolean)
            End Get
            Set
                Me("Aimentation_Intelligente") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Smart_Tags() As Boolean
            Get
                Return CType(Me("Smart_Tags"),Boolean)
            End Get
            Set
                Me("Smart_Tags") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Réduire_Panneau_Lateral_WindowsDesigner() As Boolean
            Get
                Return CType(Me("Réduire_Panneau_Lateral_WindowsDesigner"),Boolean)
            End Get
            Set
                Me("Réduire_Panneau_Lateral_WindowsDesigner") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Réduire_Panneau_Lateral_FunctionEditor() As Boolean
            Get
                Return CType(Me("Réduire_Panneau_Lateral_FunctionEditor"),Boolean)
            End Get
            Set
                Me("Réduire_Panneau_Lateral_FunctionEditor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Barre_Etat() As Boolean
            Get
                Return CType(Me("Barre_Etat"),Boolean)
            End Get
            Set
                Me("Barre_Etat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Minimiser_Ruban() As Boolean
            Get
                Return CType(Me("Minimiser_Ruban"),Boolean)
            End Get
            Set
                Me("Minimiser_Ruban") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Barre_Acces_Rapide_Dessous() As Boolean
            Get
                Return CType(Me("Barre_Acces_Rapide_Dessous"),Boolean)
            End Get
            Set
                Me("Barre_Acces_Rapide_Dessous") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Activer_Reconnaissance_Vocale() As Boolean
            Get
                Return CType(Me("Activer_Reconnaissance_Vocale"),Boolean)
            End Get
            Set
                Me("Activer_Reconnaissance_Vocale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Numerotation_Lignes() As Boolean
            Get
                Return CType(Me("Numerotation_Lignes"),Boolean)
            End Get
            Set
                Me("Numerotation_Lignes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Colorisation_Syntaxe() As Boolean
            Get
                Return CType(Me("Colorisation_Syntaxe"),Boolean)
            End Get
            Set
                Me("Colorisation_Syntaxe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Activer_Aero() As Boolean
            Get
                Return CType(Me("Activer_Aero"),Boolean)
            End Get
            Set
                Me("Activer_Aero") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FormState() As Integer
            Get
                Return CType(Me("FormState"),Integer)
            End Get
            Set
                Me("FormState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Projets_Recents() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Projets_Recents"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Projets_Recents") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Suivre_Souris_Regle() As Boolean
            Get
                Return CType(Me("Suivre_Souris_Regle"),Boolean)
            End Get
            Set
                Me("Suivre_Souris_Regle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Ouvrir() As Boolean
            Get
                Return CType(Me("QAT_Ouvrir"),Boolean)
            End Get
            Set
                Me("QAT_Ouvrir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Enregistrer_Sous() As Boolean
            Get
                Return CType(Me("QAT_Enregistrer_Sous"),Boolean)
            End Get
            Set
                Me("QAT_Enregistrer_Sous") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Enregistrer_Tout() As Boolean
            Get
                Return CType(Me("QAT_Enregistrer_Tout"),Boolean)
            End Get
            Set
                Me("QAT_Enregistrer_Tout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Fermer() As Boolean
            Get
                Return CType(Me("QAT_Fermer"),Boolean)
            End Get
            Set
                Me("QAT_Fermer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Copier() As Boolean
            Get
                Return CType(Me("QAT_Copier"),Boolean)
            End Get
            Set
                Me("QAT_Copier") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Coller() As Boolean
            Get
                Return CType(Me("QAT_Coller"),Boolean)
            End Get
            Set
                Me("QAT_Coller") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Couper() As Boolean
            Get
                Return CType(Me("QAT_Couper"),Boolean)
            End Get
            Set
                Me("QAT_Couper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Annuler() As Boolean
            Get
                Return CType(Me("QAT_Annuler"),Boolean)
            End Get
            Set
                Me("QAT_Annuler") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Retablir() As Boolean
            Get
                Return CType(Me("QAT_Retablir"),Boolean)
            End Get
            Set
                Me("QAT_Retablir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QAT_Generer() As Boolean
            Get
                Return CType(Me("QAT_Generer"),Boolean)
            End Get
            Set
                Me("QAT_Generer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WindowTheme() As Integer
            Get
                Return CType(Me("WindowTheme"),Integer)
            End Get
            Set
                Me("WindowTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property Edition() As Integer
            Get
                Return CType(Me("Edition"),Integer)
            End Get
            Set
                Me("Edition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Activer_Significations_Sonores() As Boolean
            Get
                Return CType(Me("Activer_Significations_Sonores"),Boolean)
            End Get
            Set
                Me("Activer_Significations_Sonores") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Autoriser_Envoyer_Informations() As Boolean
            Get
                Return CType(Me("Autoriser_Envoyer_Informations"),Boolean)
            End Get
            Set
                Me("Autoriser_Envoyer_Informations") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Autoriser_Donnees_Reconnaissances_Vocale() As Boolean
            Get
                Return CType(Me("Autoriser_Donnees_Reconnaissances_Vocale"),Boolean)
            End Get
            Set
                Me("Autoriser_Donnees_Reconnaissances_Vocale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Autoriser_Erreur_Generation() As Boolean
            Get
                Return CType(Me("Autoriser_Erreur_Generation"),Boolean)
            End Get
            Set
                Me("Autoriser_Erreur_Generation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Afficher_Zoom_Bar() As Boolean
            Get
                Return CType(Me("Afficher_Zoom_Bar"),Boolean)
            End Get
            Set
                Me("Afficher_Zoom_Bar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Correcteur_Orthographe() As Boolean
            Get
                Return CType(Me("Correcteur_Orthographe"),Boolean)
            End Get
            Set
                Me("Correcteur_Orthographe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Ecran_Demarrage() As Boolean
            Get
                Return CType(Me("Ecran_Demarrage"),Boolean)
            End Get
            Set
                Me("Ecran_Demarrage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Temps_Pause() As Boolean
            Get
                Return CType(Me("Temps_Pause"),Boolean)
            End Get
            Set
                Me("Temps_Pause") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SoftwareZator.My.MySettings
            Get
                Return Global.SoftwareZator.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
