'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.237
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VelerSoftware.SQLServerPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add_table_column() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_table_column", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property add_table_row() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_table_row", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property change_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("change_database", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property connect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property connexion_status() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connexion_status", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property create_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create_database", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property create_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create_table", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property delete_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_table", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property delete_table_row() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_table_row", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property disconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconnect", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property gat_tables() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gat_tables", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property get_databases() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_databases", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property get_table_cell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_table_cell", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property get_table_cells() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_table_cells", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property get_table_columns_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_table_columns_list", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property get_table_row() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_table_row", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property get_table_rows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_table_rows", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property load_table_datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load_table_datagridview", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property rename_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rename_table", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property run_request() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run_request", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property save_table_datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_table_datagridview", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
