'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.17929
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VelerSoftware.GeneralPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_ctrl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_ctrl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property afficher_balloon_notifyicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("afficher_balloon_notifyicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property afficher_contextmenustrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("afficher_contextmenustrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Afficher_Un_Message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afficher_Un_Message", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_colonne_datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_colonne_datagridview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_colonne_listview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_colonne_listview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_controle_flowlayoutpanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_controle_flowlayoutpanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_controle_groupbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_controle_groupbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_controle_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_controle_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_date_monthcalendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_date_monthcalendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_element_checkedlistbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_element_checkedlistbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_element_combobox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_element_combobox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_element_listbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_element_listbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_fenetre_enfant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_fenetre_enfant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_image_imagelist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_image_imagelist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_item_listview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_item_listview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_ligne_datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_ligne_datagridview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_noeud_treeview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_noeud_treeview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_onglet_tabcontrol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_onglet_tabcontrol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajouter_point_diagramme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter_point_diagramme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property annuler_editeur_texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("annuler_editeur_texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arreter_backgroundworker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arreter_backgroundworker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arreter_timer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arreter_timer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arreterapplicationSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arreterapplicationSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property assigner_donnee_serialiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assigner_donnee_serialiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boucle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boucle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calcul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calcul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Changer_Couleur_Fond_Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Changer_Couleur_Fond_Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Changer_Couleur_Texte_Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Changer_Couleur_Texte_Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property charger_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("charger_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkedlistbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkedlistbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coller_editeur_texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coller_editeur_texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ColorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property combobox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("combobox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property commandes_vb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("commandes_vb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comparer_deux_dates() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comparer_deux_dates", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property convertir_valeur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("convertir_valeur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copier_dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copier_dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copier_editeur_texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copier_editeur_texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copier_fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copier_fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copyright_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copyright_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property couper_editeur_texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("couper_editeur_texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creer_cle_registre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creer_cle_registre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creer_dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creer_dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creer_fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creer_fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creer_valeur_registre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creer_valeur_registre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property declarer_api() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("declarer_api", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property declarer_propriete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("declarer_propriete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Decrypter_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Decrypter_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Definir_Titre_Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Definir_Titre_Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Demander_Utilisateur_Ecrire_Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Demander_Utilisateur_Ecrire_Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarrer_backgroundworker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarrer_backgroundworker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarrer_timer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarrer_timer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deplacer_dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deplacer_dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deplacer_fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deplacer_fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property determiner_backgroundworker_execution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("determiner_backgroundworker_execution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Determiner_Connecter_Internet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Determiner_Connecter_Internet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property determiner_dossier_existe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("determiner_dossier_existe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property determiner_fichier_existe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("determiner_fichier_existe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property determiner_valeur_existe_variable_tableau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("determiner_valeur_existe_variable_tableau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property down_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ecrire_Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ecrire_Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Encrypter_Ficher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Encrypter_Ficher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enregistrer_donnee_serialisable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enregistrer_donnee_serialisable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property envoyer_email() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("envoyer_email", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property etiquette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etiquette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property execute_function() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("execute_function", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property executer_api() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("executer_api", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property executer_fonction_controle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("executer_fonction_controle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property executer_fonction_propriete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("executer_fonction_propriete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property executer_fonction_variable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("executer_fonction_variable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property executer_msdos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("executer_msdos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fermer_fenetre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fermer_fenetre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fermer_fenetre_enfant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fermer_fenetre_enfant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flowlayoutpanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flowlayoutpanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FolderBrowserDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderBrowserDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fonction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fonction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FontDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property generer_nombre_aleatoire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generer_nombre_aleatoire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Groupe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Groupe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Incrementer_Date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Incrementer_Date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jouer_un_son() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jouer_un_son", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lancer_processus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lancer_processus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lire_Fichier_Texte_Entier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lire_Fichier_Texte_Entier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lire_Fichier_Texte_Ligne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lire_Fichier_Texte_Ligne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lire_valeur_registre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lire_valeur_registre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property listbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property listview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_item_listview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_item_listview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_point_diagramme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_point_diagramme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_propriete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_propriete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_propriete_donne_serialisable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_propriete_donne_serialisable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_propriete_parametre_fonction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_propriete_parametre_fonction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_propriete_propriété() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_propriete_propriété", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modifier_variable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier_variable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property naviguer_webbrowser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("naviguer_webbrowser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nom_complet_os() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nom_complet_os", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nom_utilisateur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nom_utilisateur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nouvelle_date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nouvelle_date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_argument_demarrage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_argument_demarrage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obtenir_Date_Texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obtenir_Date_Texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_date_windows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_date_windows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obtenir_Extension_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obtenir_Extension_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obtenir_Fenêtres_Ouvertes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obtenir_Fenêtres_Ouvertes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_index_valeur_variable_tableau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_index_valeur_variable_tableau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_information_dates() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_information_dates", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obtenir_Information_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obtenir_Information_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obtenir_IP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obtenir_IP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_ligne_datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_ligne_datagridview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_liste_fichier_dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_liste_fichier_dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_nom_projet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_nom_projet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_propriété_controle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_propriété_controle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_propriete_donnee_serialisable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_propriete_donnee_serialisable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_propriete_parametre_fonction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_propriete_parametre_fonction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_propriété_propriete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_propriété_propriete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_propriete_valeur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_propriete_valeur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Obtenir_Taille_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obtenir_Taille_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_type_propriete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_type_propriete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obtenir_type_variable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obtenir_type_variable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFileDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ouvrir_fenetre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ouvrir_fenetre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ouvrir_fichier_serialiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ouvrir_fichier_serialiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panneau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panneau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pause_Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property precedent_webbrowser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("precedent_webbrowser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property progression_backgroundworker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progression_backgroundworker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redemarrer_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redemarrer_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Renommer_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Renommer_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property retablir_editeur_texte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retablir_editeur_texte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property retourner_valeur_fonction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retourner_valeur_fonction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Run_PowerShell_Command() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Run_PowerShell_Command", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SaveFileDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFileDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property si_alors_sinon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("si_alors_sinon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property societe_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("societe_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sortir_boucle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortir_boucle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sortir_sub() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortir_sub", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stopper_Son() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stopper_Son", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property suivant_webbrowser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suivant_webbrowser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_controle_flowlayoutpanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_controle_flowlayoutpanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_controle_groupbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_controle_groupbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_controle_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_controle_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_date_monthcalendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_date_monthcalendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Supprimer_Dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Supprimer_Dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Supprimer_Fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Supprimer_Fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_item_checkedlistbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_item_checkedlistbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_item_combobox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_item_combobox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_item_listbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_item_listbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_item_listview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_item_listview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_item_treeview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_item_treeview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_ligne_datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_ligne_datagridview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_onglet_tabcontrol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_onglet_tabcontrol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_point_diagramme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_point_diagramme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supprimer_valeur_registre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supprimer_valeur_registre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tabcontrol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tabcontrol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property telecharger_fichier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("telecharger_fichier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_lenght() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_lenght", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_lower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_lower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_split() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_split", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_upper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_upper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texte_replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texte_replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textremoveSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textremoveSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tuer_processus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tuer_processus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property up_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_monthcalendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_monthcalendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property verr_maj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("verr_maj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property version_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("version_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property version_net() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("version_net", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property version_windows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("version_windows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vider_console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vider_console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vider_variable_tableau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vider_variable_tableau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
