//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelerSoftware.SZC.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VelerSoftware.SZC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _namespace {
            get {
                object obj = ResourceManager.GetObject("_namespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les fonctions.
        /// </summary>
        internal static string AfficherlesfonctionsTexte {
            get {
                return ResourceManager.GetString("AfficherlesfonctionsTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show functions.
        /// </summary>
        internal static string AfficherlesfonctionsTexte_EN {
            get {
                return ResourceManager.GetString("AfficherlesfonctionsTexte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string AnnulerTexte {
            get {
                return ResourceManager.GetString("AnnulerTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        internal static string AnnulerTexte_EN {
            get {
                return ResourceManager.GetString("AnnulerTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap assembly {
            get {
                object obj = ResourceManager.GetObject("assembly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BringToFrontHS {
            get {
                object obj = ResourceManager.GetObject("BringToFrontHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coller.
        /// </summary>
        internal static string CollerTexte {
            get {
                return ResourceManager.GetString("CollerTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste.
        /// </summary>
        internal static string CollerTexte_EN {
            get {
                return ResourceManager.GetString("CollerTexte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copier.
        /// </summary>
        internal static string CopierTexte {
            get {
                return ResourceManager.GetString("CopierTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        internal static string CopierTexte_EN {
            get {
                return ResourceManager.GetString("CopierTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap copy_small {
            get {
                object obj = ResourceManager.GetObject("copy_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couper.
        /// </summary>
        internal static string CouperTexte {
            get {
                return ResourceManager.GetString("CouperTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut.
        /// </summary>
        internal static string CouperTexte_EN {
            get {
                return ResourceManager.GetString("CouperTexte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un évènement.
        /// </summary>
        internal static string CréerunévènementTexte {
            get {
                return ResourceManager.GetString("CréerunévènementTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create event.
        /// </summary>
        internal static string CréerunévènementTexte_EN {
            get {
                return ResourceManager.GetString("CréerunévènementTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DVSplit {
            get {
                object obj = ResourceManager.GetObject("DVSplit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La fonction n&apos;a pas de code IL.
        /// </summary>
        internal static string Eval_IL {
            get {
                return ResourceManager.GetString("Eval_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function does not have IL code.
        /// </summary>
        internal static string Eval_IL_EN {
            get {
                return ResourceManager.GetString("Eval_IL_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;évaluation ne peut être arrêté.
        /// </summary>
        internal static string Eval_Not_Stopped {
            get {
                return ResourceManager.GetString("Eval_Not_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation can not be stopped.
        /// </summary>
        internal static string Eval_Not_Stopped_EN {
            get {
                return ResourceManager.GetString("Eval_Not_Stopped_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;évaluer la valeur avec un projet optimisé.
        /// </summary>
        internal static string Eval_Optimized {
            get {
                return ResourceManager.GetString("Eval_Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not evaluate in optimized code.
        /// </summary>
        internal static string Eval_Optimized_EN {
            get {
                return ResourceManager.GetString("Eval_Optimized_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le processus s&apos;est fermé.
        /// </summary>
        internal static string Eval_Process_Exited {
            get {
                return ResourceManager.GetString("Eval_Process_Exited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process exited.
        /// </summary>
        internal static string Eval_Process_Exited_EN {
            get {
                return ResourceManager.GetString("Eval_Process_Exited_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;évaluer après un débordement de pile.
        /// </summary>
        internal static string Eval_Stack_Overflow {
            get {
                return ResourceManager.GetString("Eval_Stack_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not evaluate after stack overflow.
        /// </summary>
        internal static string Eval_Stack_Overflow_EN {
            get {
                return ResourceManager.GetString("Eval_Stack_Overflow_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun fil approprié pour l&apos;évaluation.
        /// </summary>
        internal static string Eval_Suitable_Thread {
            get {
                return ResourceManager.GetString("Eval_Suitable_Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No suitable thread for evaluation.
        /// </summary>
        internal static string Eval_Suitable_Thread_EN {
            get {
                return ResourceManager.GetString("Eval_Suitable_Thread_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps mort.
        /// </summary>
        internal static string Eval_Timeout {
            get {
                return ResourceManager.GetString("Eval_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout.
        /// </summary>
        internal static string Eval_Timeout_EN {
            get {
                return ResourceManager.GetString("Eval_Timeout_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat inconnu.
        /// </summary>
        internal static string Eval_Unknow_State {
            get {
                return ResourceManager.GetString("Eval_Unknow_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow state.
        /// </summary>
        internal static string Eval_Unknow_State_EN {
            get {
                return ResourceManager.GetString("Eval_Unknow_State_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;objet est dans un mauvais domaine d&apos;application.
        /// </summary>
        internal static string Eval_Wrong_Appdomain {
            get {
                return ResourceManager.GetString("Eval_Wrong_Appdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object is in wrong AppDomain.
        /// </summary>
        internal static string Eval_Wrong_Appdomain_EN {
            get {
                return ResourceManager.GetString("Eval_Wrong_Appdomain_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap field {
            get {
                object obj = ResourceManager.GetObject("field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fonction {
            get {
                object obj = ResourceManager.GetObject("Fonction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gest_var {
            get {
                object obj = ResourceManager.GetObject("gest_var", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning {
            get {
                object obj = ResourceManager.GetObject("lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] loading_icon {
            get {
                object obj = ResourceManager.GetObject("loading_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point d&apos;arrêt rencontré à la ligne {0} à {1}..
        /// </summary>
        internal static string MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAt {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit breakpoint at line {0} in {1}..
        /// </summary>
        internal static string MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAt_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAt_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point d&apos;arrêt rencontré à la ligne {0} à {1} parce que {2}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAtBecause {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAtBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit breakpoint at line {0} in {1} because {2}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAtBecause_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_Conditional_Breakpoints_BreakpointHitAtBecause_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à à {0}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_ExceptionForm_LineFormat_NoSymbols {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_ExceptionForm_LineFormat_NoSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at {0}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_ExceptionForm_LineFormat_NoSymbols_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_ExceptionForm_LineFormat_NoSymbols_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à à {0} dans {1}: ligne {2}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_ExceptionForm_LineFormat_Symbols {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_ExceptionForm_LineFormat_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at {0} in {1}:line {2}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_ExceptionForm_LineFormat_Symbols_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_ExceptionForm_LineFormat_Symbols_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_BaseClass {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_BaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_BaseClass_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_BaseClass_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de convertir {0} en {1}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CannotSetValue_BadFormat {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CannotSetValue_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not convert {0} to {1}.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CannotSetValue_BadFormat_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CannotSetValue_BadFormat_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;assigner la valeur.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CannotSetValue_Title {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CannotSetValue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not set value.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CannotSetValue_Title_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CannotSetValue_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;assigner la valeur.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CannotSetValue_UnknownError {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CannotSetValue_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not set value.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CannotSetValue_UnknownError_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CannotSetValue_UnknownError_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copier la valeur dans le presse-papiers.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CopyToClipboard {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy value to clipboard.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_CopyToClipboard_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_CopyToClipboard_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Membres No-Public.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_NonPublicMembers {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_NonPublicMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non-Public members.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_NonPublicMembers_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_NonPublicMembers_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Membres Static No-Public.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_NonPublicStaticMembers {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_NonPublicStaticMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non-Public Static members.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_NonPublicStaticMembers_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_NonPublicStaticMembers_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;erreur complète....
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_ShowFullError {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_ShowFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show full error....
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_ShowFullError_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_ShowFullError_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Membres Static.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_StaticMembers {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_StaticMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Static members.
        /// </summary>
        internal static string MainWindow_Windows_Debug_LocalVariables_StaticMembers_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_LocalVariables_StaticMembers_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas avancer parce qu&apos;il n&apos;y a pas de fonction active sélectionnée.
        /// </summary>
        internal static string MainWindow_Windows_Debug_Threads_CannotStepNoActiveFunction {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_Threads_CannotStepNoActiveFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot step because there is no active function selected.
        /// </summary>
        internal static string MainWindow_Windows_Debug_Threads_CannotStepNoActiveFunction_EN {
            get {
                return ResourceManager.GetString("MainWindow_Windows_Debug_Threads_CannotStepNoActiveFunction_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre au premier plan.
        /// </summary>
        internal static string MettreaupremierplanTexte {
            get {
                return ResourceManager.GetString("MettreaupremierplanTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bring to front.
        /// </summary>
        internal static string MettreaupremierplanTexte_EN {
            get {
                return ResourceManager.GetString("MettreaupremierplanTexte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre en arrière plan.
        /// </summary>
        internal static string MettreenarrièreplanTexte {
            get {
                return ResourceManager.GetString("MettreenarrièreplanTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send toback.
        /// </summary>
        internal static string MettreenarrièreplanTexte_EN {
            get {
                return ResourceManager.GetString("MettreenarrièreplanTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste_sma {
            get {
                object obj = ResourceManager.GetObject("paste_sma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Propriété {
            get {
                object obj = ResourceManager.GetObject("Propriété", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés.
        /// </summary>
        internal static string PropriétésTexte {
            get {
                return ResourceManager.GetString("PropriétésTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        internal static string PropriétésTexte_EN {
            get {
                return ResourceManager.GetString("PropriétésTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ProtectFormHS {
            get {
                object obj = ResourceManager.GetObject("ProtectFormHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rétablir.
        /// </summary>
        internal static string RetablirTexte {
            get {
                return ResourceManager.GetString("RetablirTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo.
        /// </summary>
        internal static string RetablirTexte_EN {
            get {
                return ResourceManager.GetString("RetablirTexte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner.
        /// </summary>
        internal static string SelectionnerTexte {
            get {
                return ResourceManager.GetString("SelectionnerTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        internal static string SelectionnerTexte_EN {
            get {
                return ResourceManager.GetString("SelectionnerTexte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner tout.
        /// </summary>
        internal static string SelectionnerToutTexte {
            get {
                return ResourceManager.GetString("SelectionnerToutTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        internal static string SelectionnerToutTexte_EN {
            get {
                return ResourceManager.GetString("SelectionnerToutTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SendToBackHS {
            get {
                object obj = ResourceManager.GetObject("SendToBackHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string SupprimerTexte {
            get {
                return ResourceManager.GetString("SupprimerTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string SupprimerTexte_EN {
            get {
                return ResourceManager.GetString("SupprimerTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SZW_Icon_16 {
            get {
                object obj = ResourceManager.GetObject("SZW_Icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérouiller les contrôles.
        /// </summary>
        internal static string VérouillerlescontrôlesTexte {
            get {
                return ResourceManager.GetString("VérouillerlescontrôlesTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock.
        /// </summary>
        internal static string VérouillerlescontrôlesTexte_EN {
            get {
                return ResourceManager.GetString("VérouillerlescontrôlesTexte_EN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap vide {
            get {
                object obj = ResourceManager.GetObject("vide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de démarrer le processus..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_CannotStartProcess {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_CannotStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not start process..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_CannotStartProcess_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_CannotStartProcess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;effectuer l&apos;action à cause de certains processus de débogage..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_Debugging {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not perform action because some process is debugged..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_Debugging_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_Debugging_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de démarrer le débogueur de SoftwareZator car le débogueur du noyau Windows est activé. Pour désactiver le débogueur de noyau, supprimez le commutateur &quot;/debug&quot; dans le fichier Boot.ini, puis redémarrez votre ordinateur..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_KernelDebuggerEnabled {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_KernelDebuggerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not start SoftwareZator debugger because Windows kernel debugger is enabled.  To disable the kernel debugger, remove the switch &quot;/debug&quot; from the file Boot.ini and reboot your computer..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_KernelDebuggerEnabled_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_KernelDebuggerEnabled_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le débogage de. NET Framework 1.0 n&apos;est pas supporté..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_Net10NotSupported {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_Net10NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debugging of .NET Framework 1.0 programs is not supported..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_Net10NotSupported_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_Net10NotSupported_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;effectuer l&apos;action car aucun processus de débogage n&apos;est en cours..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_NotDebugging {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_NotDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not perform action because no process is debugged..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_NotDebugging_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_NotDebugging_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;effectuer l&apos;action car le processus est en pause..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_ProcessPaused {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_ProcessPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not perform action because process is paused..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_ProcessPaused_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_ProcessPaused_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;effectuer l&apos;action car le processus est en fonctionnement..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_ProcessRunning {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_ProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not perform action because process is running..
        /// </summary>
        internal static string XML_MainMenu_DebugMenu_Error_ProcessRunning_EN {
            get {
                return ResourceManager.GetString("XML_MainMenu_DebugMenu_Error_ProcessRunning_EN", resourceCulture);
            }
        }
    }
}
